<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loguin</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
<h1 class="text-3xl font-bold underline">
    Hello world!
  </h1>
<section class="index-login">
        <div class="index-login-signup">
            <h4>SING UP</h4>
            <P>Don't have an account yet? Sing up here!</P>
            <form action="/web/signup" method="POST">
                <input type="text" name="name" placeholder="name">
                <input type="text" name="surname" placeholder="surname">
                <input type="text" name="userName" placeholder="userName">
                <input type="text" name="email" placeholder="email">
                <input type="password" name="pw" placeholder="pw">
                <br>
                <button type="submit" name="submit">SING UP</button>
            </form>
        </div>
    </div>
</section>
    
</body>
</html>